name: Sample file for testing
on:
  push:
    branches:
        - 'main' 
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        id: 'auth'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      - name: Set up Docker to use gcloud 
        run: |
            gcloud auth configure-docker asia-south-1-docker.pkg.dev
      - name: Build Docker Image
        run: |
          docker build -t asia-south-1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/test-repo/hello_python:latest ./src
      - name: Push Docker Image
        run: |
          docker push asia-south-1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/test-repo/hello_python:latest
      - name: Print Image URL
        run: |
          echo "Print IMage URL"
          echo "asia-south-1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/test-repo/hello_python:latest"

        
            
