name: Sample file for testing
on:
  push:
    branches:
        - 'main' 
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        id: 'auth'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      - name: Print Hello
        run: |
            gcloud config set project ${{ secrets.PROJECT_ID }}
            echo "Hello From GCP"   
            
